[package]
name = "typst-shim"
description = "A compatibility layer for Typst release and mainline versions."
authors = ["The Typst Project Developers"]
version = "0.13.12"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = []
nightly = []

[dependencies]
typst-syntax.workspace = true
typst-eval.workspace = true
typst.workspace = true
cfg-if.workspace = true
comemo.workspace = true

[lints]
workspace = true
