[package]
name = "typlite"
description = "Converts a subset of typst to markdown."
categories = ["compilers"]
keywords = ["language", "typst"]
authors.workspace = true
version.workspace = true
license.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "typlite"
path = "src/main.rs"
required-features = ["cli"]
test = false
doctest = false
bench = false
doc = false

[dependencies]
base64.workspace = true
clap = { workspace = true, optional = true }
comemo.workspace = true
ecow.workspace = true
tinymist-analysis.workspace = true
tinymist-std.workspace = true
tinymist-derive.workspace = true
tinymist-project = { workspace = true, features = ["lsp"] }
typst.workspace = true
typst-svg.workspace = true
typst-syntax.workspace = true
typst-html.workspace = true
docx-rs = { git = "https://github.com/bokuweb/docx-rs.git", version = "0.4.18-rc19" }
image = "0.25.6"
regex.workspace = true
resvg = "0.45.1"
md5 = "0.7.0"
cmark-writer = "0.4.0"

[dev-dependencies]
insta.workspace = true
regex.workspace = true
tinymist-tests.workspace = true

[features]
default = ["cli", "embed-fonts", "no-content-hint"]
clap = ["dep:clap"]
cli = ["clap", "clap/wrap_help"]
no-content-hint = ["tinymist-project/no-content-hint"]

# Embeds Typst's default fonts for
# - text (Linux Libertine),
# - math (New Computer Modern Math), and
# - code (Deja Vu Sans Mono)
# and additionally New Computer Modern for text
# into the binary.
embed-fonts = ["tinymist-project/fonts"]

# [lints]
# workspace = true
